project:
  type: website

website:
  title: "Warren James"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - text: "About"
        href: about/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

