project:
  type: website
  output-dir: docs

website:
  title: "Warren James"
  navbar:
    tools:
      - icon: github
        href: https://github.com/warren-james
      - icon: instagram
        href: https://www.instagram.com/warrenrgjames/
    right:
      - href: index.qmd
        text: "Home"
      - text: "About"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - href: supMat/index.qmd
        text: "Supplementary Materials"
      - href: papers/index.qmd
        text: "Papers"

format:
  html:
    theme:
      light: 
        - cosmo
      dark: 
        - superhero
    lightbox: true
    link-external-icon: true
    link-external-newwindow: true
   # css: styles.css
   # toc: true

# include-in-header: move-toggle.Rhtml

editor: source

