project:
  type: website
  output-dir: docs

website:
  title: "Warren James"
  navbar:
    tools:
      - icon: github
        href: https://github.com/warren-james
    right:
      - href: index.qmd
        text: "Home"
      - text: "About"
        href: about/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - href: supMat/index.qmd
        text: "Supplementary Materials"

format:
  html:
    theme:
      light: 
        - cosmo
      dark: 
        - superhero
   # css: styles.css
   # toc: true

# include-in-header: move-toggle.Rhtml

editor: source

