---
title: "About"
---

My name's Warren James and my career in academia started at the university of Aberdeen in the Psychology department. After working for a fast food chain that I will not name (but will say specialises fried chicken from a state in America beginning with K), I was fortunate to be offered the chance to work as a research assistant for a summer project looking at eye movements and decision making. From there, I went on to complete my PhD continuing this train of work. During this time, I spent my days learning about the various ways statistics can be used to help us make sense of complicated data and offer insight into what is happening. Unfortunately, I also saw that "dark side" of statistics when it is used inappropriately leading to some unusual claims that weren't supported by evidence. As a result of this (and with the firm guidance of my supervisors), I have decided to join the push to raise the standards of research by championing open practices and the use of open-source software to help us all become better researchers. I try to avoid getting on a soap box as much as possible, but like most academics it would appear I like the sound of my own opinion/voice. Having said that, I am always happy to be wrong. 

Currently, I work in Epidemiolgy as part of the [Centre for Musculoskeletal and Pain Epidemiology](https://www.abdn.ac.uk/iahs/research/epidemiology/index.php) and the [Biostatistics and Health Data Science Group](https://www.abdn.ac.uk/iahs/research/biostatistics-and-health-data-sciences-3072.php) at the [University of Aberdeen](https://www.abdn.ac.uk/). In this role, I apply various statistical techniques to answer clinically relevant questions with the hope that this allows us to understand how health care services can be provided to improve outcomes for patients. 

Apart from being a number nerd, I also do a bit of music which I'm hoping to start sharing soon. Shameless self promotion on what is meant to be my professional website, but then it is __*my*__ website so I can plug what I want. 

